### ISSUE TITLE
Search results displaying slowly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_webclient#486] opened 2015-08-18 09:25 UTC
The display of search results is very slow even though loklak_server provides instant results. Please fix and document the issue here.

![screenshot from 2015-08-18 11 26 57](https://cloud.githubusercontent.com/assets/1583873/9326707/15bf1318-459c-11e5-87ed-b91a5f4d1482.png)

**Comment by fuksi** [comment] 2015-08-18 18:08
I did a manual profiling and the processing times are, as you can see, 0.015s & 0.026s. (The time in console in from between when user presses enter & when the result is shown - in miliseconds). 

![2015-08-18 20_52_58-photos](https://cloud.githubusercontent.com/assets/6878677/9338149/e062dbaa-45eb-11e5-861b-08c076ca2b00.png)

The test was done in local. Loklak server (live) takes quite long to load from my location. You can also also quickly see it yourself by: open dev console, choose tab `network`, filter by `script` (all marked in the screenshot), and notice how long it takes when a response is received from `search.json` until the result is shown (which is very fast but still you can see it).

![2015-08-18 21_04_14-photos](https://cloud.githubusercontent.com/assets/6878677/9338363/0a228e4e-45ed-11e5-9628-41e9008c049c.png)

**Comment by mariobehling** [comment] 2015-08-18 18:17
Ok, thanks!

@Orbiter What are your ideas about this?

**Comment by mariobehling** [comment] 2015-08-18 21:08
@fuksi The issue is also, that results are sometimes not displayed at all and the page stops loading on Firefox. Entering the same search term and hitting enter - no result.

![screenshot from 2015-08-18 23 07 10](https://cloud.githubusercontent.com/assets/1583873/9342752/e6efa61c-45fd-11e5-86db-9d2032105fb2.png)

**Comment by fuksi** [comment] 2015-08-18 22:02
Oh, about this, I forgot to put it to discussion. Anyway, when a user opens a search link, say: http://loklak.net/search?q=london, there are at least 2 requests are made:
- One to get the trends (the 1st successul one in the screenshot. Nevermind the 2nd, it just hello.js non-critical bug that it authenticates twice)
- One to get the search results (the 3rd request).

The problem is, even two requests are for different purposes, they happens to target the same servlet (search.json), which has anti-DDos settings, which prevents consecutive requests, hence the failure in search result. 

![image](https://cloud.githubusercontent.com/assets/6878677/9343741/76556662-460c-11e5-919c-935e58228488.png)

**Solution**: I made a simple patch/workaround to delay the request for trends a little bit. Will be included in the next PR.

Even though it is a workaround, I think it suffices (because it works), since enhancement from the server can complicate the anti-DDos settings.

**Comment by mariobehling** [comment] 2015-08-19 06:03
@fuksi How long is the delay? Please proceed with the work around and let's see @Orbiter's input.

@Orbiter What do you think?

**Comment by fuksi** [comment] 2015-08-19 13:32
The delay is 3s. The delay is not referring to when a search is done. The trends is requested when application is loaded, regardless of the view. It is requested once and used for all view.

**Comment by mariobehling** [comment] 2015-08-19 13:35
3 seconds or 3 miliseconds? 

Three seconds is an eternity for the web! What other solutions do you propose?

**Comment by fuksi** [comment] 2015-08-19 15:16
3 seconds was unnecessary. I reduced it 1 second. I just tested on live and it is not block by DDos :) (the delay can be seen in difference in green bars position).
![image](https://cloud.githubusercontent.com/assets/6878677/9360268/fdec2a7a-469d-11e5-842d-42b1e1309f79.png)

**Comment by mariobehling** [comment] 2015-08-20 09:51
Actually, everyone is aiming for improving on miliseconds and here we delay the request. It really does not make sense. What other options are there? Can the trends be cached regularly and handled independently from other requests?

**Comment by fuksi** [comment] 2015-08-20 16:29
As I explained early, with the current server state, making 2 requests at the same time to the same servlet is not possible, and I think it's absolutely normal for security reason. 

The only solution is if there is a separate servlet for trends aggregation. @Orbiter can give more info on this when he's back :)

Although I don't believe UX is changed/nor bad because of this delay, because
- Most view are not using trends immediately on load, for example for home view, map is show first, if you hide the map to show the timeline, the trends are already there.
- In search view: getting the trends are relatively fast comparing to the search result. Average response time + delay is around 1.2s, while search result, based on what I've seen, takes about 2s minimum. Then the trends will still show before the search result.

**Comment by mariobehling** [comment] 2015-08-20 17:08
Search results should be immediate. Speed is very important. We got feedback of a number of people complaining about the slow speed. Let's see with @Orbiter if a separate servlet could be the solution. Moving this to M4.5 then.

**Closed** 2016-09-10 13:34 UTC
Labels: bug, Search
