### ISSUE TITLE
README states error generating command for npm

### ISSUE THREAD

**Issue by simsausaurabh** [fossasia/loklak_webclient#625] opened 2018-02-16 10:51 UTC
`sudo npm install -g gulp` command mentioned in README.md leads to core dumped error.

![screenshot from 2018-02-16 16-11-17](https://user-images.githubusercontent.com/16608864/36304353-57746736-1335-11e8-9427-2173d3a54d27.png)

**Comment by singhpratyush** [comment] 2018-02-16 11:58
Works for me. Using `sudo` is the correct way to do global installations as you will be writing files at locations which require superuser permission. The cause of error should be something else in your case, please recheck.

Closing.

**Closed as completed by singhpratyush** 2018-02-16 11:58 UTC
